Feature/issue 241/duration time
ksquareincmx/conference-client pull request #255
Opened 2019-08-28 21:59 UTC by JessicaBuenfilSolis

2019-08-28 22:00 UTC, JessicaBuenfilSolis commented
#241

2019-08-28 23:26 UTC, mishelashala requested changes

2019-08-28 23:26 UTC, mishelashala commented on src/components/Modals/CreateMeeting/BookingForm.jsx
> +        () => this.enableEndTimeSelect()
you'r just forwarding the call, you could express the same like this:

```js
this.setState(
        this.updateMeetingDuration,
        this.enableEndTimeSelect
)
```

2019-08-28 23:26 UTC, mishelashala commented on src/components/Modals/CreateMeeting/BookingForm.jsx
> +  updateMeetingDuration = ({ startTime, endTime, timesMeetingDuration }) => {
move function out of component:

```jsx
// rename `timesMeetingDuration` to just `meetingDuration`
const getMeetingDuration = ({ startTime, endTime, meetingDuration }) => {
  // ... the rest of your code
  // just return times
  return times
}
```

2019-08-28 23:26 UTC, mishelashala commented on src/components/Modals/CreateMeeting/BookingForm.jsx
> +        element.selected = false;
you could express this like the following:

```jsx
const times = timesMeetingDuration.map(element => {
  return element.value === minutes ? { ...element, selected: true } : { ...elements, selected: false };
})
```

2019-08-28 23:26 UTC, mishelashala commented on src/components/Modals/CreateMeeting/BookingForm.jsx
> +      const times = [...timesMeetingDuration].map(element => {
extract logic from `setState` into a separate function

```jsx
const clearSelections = times => {
  return times.map(element => ({ ...element, selected: false }));
}

// ... some code
clearMeetingDuration = () => {
  this.setState({ timesMeetingDuration }) => {
    const times = clearSelections(timesMeetingDuration);
    return { ...prevState, timesMeetingDuration: times };
  })
}
```

2019-08-28 23:26 UTC, mishelashala commented on src/components/Modals/CreateMeeting/BookingForm.jsx
> +    const computedEndtime = moment({
extract logic into a separate function:

```js
const getEndTime = minutes = {
    const endTime = moment({
      hour: this.state.startTime.hour,
      minute: this.state.startTime.minute
    }).add(minutes, "minutes");

  return { hour: endTime.hour(), addZeros(endTime.minute())  };
}

// .. more code
setTimeDurationSelected = time => {
  const endTime = getEndTime(time.value);
  // rest of your code
}
```

2019-08-28 23:26 UTC, mishelashala commented on src/components/Modals/CreateMeeting/BookingForm.jsx
> +        const times = [...timesMeetingDuration].map(element => {
use `clearSelections`

2019-08-28 23:26 UTC, mishelashala commented on src/components/Modals/CreateMeeting/BookingForm.jsx
> +        return { timesMeetingDuration: times };
```jsx
return { ...prevState, timesMeetingDuration: times };
```

2019-08-28 23:26 UTC, mishelashala commented on src/components/Modals/CreateMeeting/BookingForm.jsx
> +      return { timesMeetingDuration: times };
```jsx
return { ...prevState, timesMeetingDuration: times };
```

2019-08-28 23:26 UTC, mishelashala commented on src/components/Modals/CreateMeeting/BookingForm.jsx
> +    this.setState(({ timesMeetingDuration }) => {
favor `prevState` when using `this.setState()` over object destructuring

2019-08-28 23:26 UTC, mishelashala commented on src/components/Modals/CreateMeeting/TimeSelect.js
> +              handleOnChangeHour(e, minute, onChangeHour);
change to 

```jsx
onChange={handleChangeHour(minute)}
```

2019-08-28 23:26 UTC, mishelashala commented on src/components/Modals/CreateMeeting/TimeSelect.js
> +function handleOnChangeMinute(e, hour, onChangeMinute) {
use currying:

```jsx
const handleChangeMinute = hour = event => {
  onChangeMinute({ hour, minute: event.target.value });
}
```

2019-08-28 23:26 UTC, mishelashala commented on src/components/Modals/CreateMeeting/TimeSelect.js
> +function handleOnChangeHour(e, minute, onChangeHour) {
change to:

```jsx
const handleChangeHour = minute = event => {
  onChangeHour({ hour: event.target.value, minute });
}
```

2019-08-28 23:26 UTC, mishelashala commented on src/components/Modals/CreateMeeting/TimeSelect.js
> +              handleOnChangeMinute(e, hour, onChangeMinute);
use currying:

```jsx
onChange={handleChangeMinute(hour)}
```
```

2019-08-28 23:26 UTC, mishelashala commented on src/components/Modals/CreateMeeting/MeetingDuration.js
> +  const timeSelectedHandler = time => {
user currying and rename:

```jsx
const handleClick = time => () => {
  onSelectItem(time);
}
```

2019-08-28 23:26 UTC, mishelashala commented on src/components/Modals/CreateMeeting/MeetingDuration.js
> +            timeSelectedHandler(time);
use currying:
```jsx
onClick={handleClick(time)}
```

2019-08-30 00:13 UTC, mishelashala requested changes

2019-08-30 00:13 UTC, mishelashala commented on src/components/Modals/CreateMeeting/BookingForm.jsx
> +  const times = [...meetingDuration].map(element => {
unnecessary variable, just return the expression

2019-08-30 00:13 UTC, mishelashala commented on src/components/Modals/CreateMeeting/BookingForm.jsx
> +  const endTime = moment({
create another function `addMinutes`

```tsx
const addMinutes = (minutes, time) => {
  // do you need to create another moment object?
  // why not simply pass time?
  return moment({
    hour: time.hour,
    minute: time.minute
  }).add(minutes, "minutes");
}

// more code...
const endTime = addMinutes(minutes, endTime);
```

2019-08-30 00:13 UTC, mishelashala commented on src/components/Modals/CreateMeeting/BookingForm.jsx
> +    console.log(startTime);
remove log

2019-08-30 00:13 UTC, mishelashala commented on src/components/Modals/CreateMeeting/BookingForm.jsx
> +      this.setState(prevState => {
you don't need  a nested `setState`:

```tsx
this.setState(prevState => {
  const { startTime, endTime, meetingDuration } = prevState;
  const updatedMeetingDuration = getMeetingDuration({ meetingDuration, startTime, endTime });
  return { ...prevState, meetingDuration: updatedMeetingDuration };
})
```

2019-08-30 00:13 UTC, mishelashala commented on src/components/Modals/CreateMeeting/BookingForm.jsx
> +      this.setState(prevState => {
same here, you don't need a nested `setState`

```tsx
this.setState(prevState => {
  const { startTime, endTime, meetingDuration } = prevState;
  const updatedMeetingDuration = getMeetingDuration({ meetingDuration, startTime, endTime });
  return { ...prevState, meetingDuration: updatedMeetingDuration };
})
```

2019-08-30 00:13 UTC, mishelashala commented on src/components/Modals/CreateMeeting/BookingForm.jsx
> +    const endTime = getEndTime(time.value, this.state.startTime);
this variable gets shadowed in the next 2 lines, do you need it here?

2019-08-30 00:13 UTC, mishelashala commented on src/components/Modals/CreateMeeting/BookingForm.jsx
> +  const minutes = moment({
move into a function called `getMinutesDiff`

```tsx
const getMinutesDiff = (startTime, endTime) => {
  // do you need to create another moment object?
  // why not simply pass endTime?
  return moment({
    hour: endTime.hour,
    minute: endTime.minute
  })
  .diff(
    // do you need to create another moment object?
    // why not simply pass startTime?
    moment({
      hour: startTime.hour,
      minute: startTime.minute
    }),
    "minute"
  );
}

const minutes = getMinutesDiff(startTime, endTime);
```

2019-08-30 00:13 UTC, mishelashala commented on src/components/Modals/CreateMeeting/BookingForm.jsx
> +      this.enableStartTimeSelect()
you don't need the extra function:

```tsx
this.setState({ date: formatDashedDate(date) }, this.enableStartTimeSelect)
```

2019-08-30 00:13 UTC, mishelashala commented on src/components/Modals/CreateMeeting/BookingForm.jsx
> +      this.setState(prevState => {
you don't need the nested `setState`

```tsx
this.setState(({ meetingDuration }) => {
  const times = clearSelections(meetingDuration);
  const idx = times.findIndex(element => {
    return element.value === time.value;
  });
  // add a validation for the index,
  // if no element it's found then the idx is
  // equal to -1
  times[idx].selected = true;
  return { ...prevState, meetingDuration: times };
})
```

2019-08-30 15:29 UTC, mishelashala requested changes

2019-08-30 15:29 UTC, mishelashala commented on src/components/Modals/CreateMeeting/BookingForm.jsx
> +      this.setState({ timesDurationDisabled: false });
no conditionals `setState`

```tsx
this.setState(prevState => {
  const timesDurationDisabled = !(updateStartTime.hour && updateStartTime.minute);
  // ...
  return {
     ...prevState,
     startTime: updateStartTime,
     meetingDuration: updatedMeetingDuration,
     timesDurationDisabled
  };
})
```

2019-08-30 16:33 UTC, mishelashala approved these changes

2019-08-30 16:33 UTC, merged