Feature/#250 appointment in the past
ksquareincmx/conference-client pull request #257
Opened 2019-09-09 16:36 UTC by JessicaBuenfilSolis

2019-09-09 16:36 UTC, JessicaBuenfilSolis commented
#250

2019-09-09 17:35 UTC, mishelashala requested changes

2019-09-09 17:35 UTC, mishelashala commented on src/components/Modals/CreateMeeting/meetingValidations.js
> +const validateIsAfterCurrentHour = (timeStart, currentTime) => {
just rename to `isAfter`

2019-09-10 21:14 UTC, mishelashala approved these changes

2019-09-10 21:14 UTC, merged